# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: University of Michigan Mars Rover Team
email: rover@umich.edu
description: > # this means to ignore newlines until "baseurl:"
    The Michigan Mars Rover team (MRover) is a student-run, multidisciplinary organization whose mission is to design and build a rover for the exploration of extraterrestrial environments. 
    Our team consists of everyone from freshman to graduate students, representing majors from the College of Engineering and the College of Literature, Science, and the Arts. 
    We strive to inspire and educate students about space, Mars exploration, and engineering, and we focus on helping students grow as engineers.
    #The Michigan Mars Rover Team is the coolest team you have ever seen. We participate in activities such as rovering all over.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mrover.org" # the base hostname & protocol for your site
twitter_username: umrover
github_username: umrover
instagram_username: umroverteam

# Our sponsors
collections:
    sponsors:

# Build settings
markdown: kramdown

#Make Jekyll build site to the docs folder, not mrover/_site
destination: ../docs